import type { Metadata } from "next";

import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { TopBar } from "@/components/Topbar";

export const metadata: Metadata = {
  title: "HireSense",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head />
        <body className="bg-gray-50 min-h-screen">
          <TopBar />
          <main className="p-6">{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
